#!/bin/zsh
# PURE_CMD_MAX_EXEC_TIME
# PURE_GIT_PULL
# PURE_GIT_UNTRACKED_DIRTY
# PURE_GIT_DELAY_DIRTY_CHECK
# PURE_GIT_DOWN_ARROW="⇣"
# PURE_GIT_UP_ARROW="⇡"
# PURE_GIT_STASH_SYMBOL="≡"

PURE_PROMPT_SYMBOL="❯"
# PURE_PROMPT_VICMD_SYMBOL="❮"
export REPORTTIME=10
